name: Build and push image to ECR
on:
  push:
    branches:
      - feature/dockerizeContracts
env:
  ECR_REPOSITORY: davinci-nft
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Installing helper packaging curl wget findutils jq"
          sudo apt-get install curl wget findutils jq

          docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:runtime
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:runtime"
          . ./run-ganache-deploy-copy-artifacts.sh
